project:
  type: website
  output-dir: docs


website:
  title: "Hiroaki Yamato| 大和弘明"
  navbar: 
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publication.qmd  




format:
  html:
    theme:
      - quartz
      - custom.scss
    include-in-header: font.html
    mainfont: Inter	
    link-external-newwindow: true
    toc: true
    toc-title: " "
    callout-appearance: simple

lang: ja


