project:
  type: website
  output-dir: docs


website:
  title: "Hiroaki Yamato| 大和弘明"
  navbar: 
    search: true
    left:
      - text: "ブログ"
        file: blogs.qmd
      - text: "連絡先"
        file: contact.qmd
      - text: "Topics"
        file: topics.qmd
      - text: "私の過去と未来"
        file: past-future.qmd
      - text: "使ってみて"
        file: try-it.qmd
      - text: "私が何をしていて何を感じているか"
        file: what-i-do-feel.qmd
      - text: "何を言っているか"
        file: what-i-say.qmd
      - text: "他の連絡先HUB"
        file: contact-hub.qmd
      - text: "一緒にやってみませんか"
        file: collaborate.qmd
      - text: "ご支援いただきたく"
        file: support.qmd  




format:
  html:
    theme:
      - quartz
      - custom.scss
    include-in-header: font.html
    mainfont: Inter	
    link-external-newwindow: true
    toc: true
    toc-title: " "
    callout-appearance: simple

lang: ja


